#!/bin/sh

# Build a Docker image with the DBT-7 kit install.

if ! which docker > /dev/null 2>&1; then
	echo "docker not in path"
	exit 1
fi

DBMS="pgsql"
PGVERSION=14

if which jq > /dev/null 2>&1; then
	PGORG="https://www.postgresql.org/versions.json"
	PGVERSION=$(curl -s ${PGORG} | jq -r 'sort | .[].major' | tail -n 1)
fi
echo "Using PostgreSQL Major Version $PGVERSION"

TOPDIR=$(dirname "$0")

# Use the return code from `docker inspect` to determine if the docker image
# needs to be created.
if ! docker inspect dbt7-base > /dev/null; then
	"${TOPDIR}/prepare-image" || exit 1
fi

TOPDIR="${TOPDIR}/.."
if ! docker build -t dbt7-${DBMS} \
		--build-arg PGVERSION="${PGVERSION}" \
		--build-arg DBMS=$DBMS \
		-f Dockerfile.database "${TOPDIR}"; then
	echo "usage: $0 [DBMS]"
	echo
	echo "DBMS options: (default: pgsql)"
	echo "  pgsql"
	exit 1
fi
